### PR TITLE
test(manage): events unit tests

### PR DESCRIPTION
**Pull request by AdityaKasar**
Unit testing of "onEvent" methods under Manage CPP SDK

### CODE REVIEW

**Review by ksentak — DISMISSED** [review]

**Comment by AdityaKasar** [comment]
test logs: 
[manage-sdk-unit-test-logs.txt](https://github.com/user-attachments/files/17394463/manage-sdk-unit-test-logs.txt)

**Review by ksentak — APPROVED** [review]
LGTM

**Comment by ksentak** [comment]
Please update branch so it is not out-of-date with `next`.

**Pull request merged**
